from __future__ import annotations

from sqlalchemy import func, select

from app.core.database import Base, SessionLocal, engine
from app.core.security import get_password_hash
from app.models.models import (
    Lesson,
    Project,
    Question,
    SATMilestone,
    SATProject,
    Subject,
    Topic,
    User,
)


def seed() -> None:
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        subjects_by_code: dict[str, Subject] = {}
        for code, name in [("SOFTDEV", "Software Development"), ("DATA", "Data Analytics")]:
            subject = db.scalar(select(Subject).where(Subject.code == code))
            if not subject:
                subject = Subject(code=code, name=name)
                db.add(subject)
                db.commit()
                db.refresh(subject)
            subjects_by_code[code] = subject

        demo_user = db.scalar(select(User).where(User.email == "student@example.com"))
        if not demo_user:
            demo_user = User(
                email="student@example.com",
                password_hash=get_password_hash("ChangeMe123!"),
                role="student",
            )
            db.add(demo_user)
            db.commit()
            db.refresh(demo_user)

        topic_templates = [
            ("Programming fundamentals", "problem solving and logic"),
            ("Data and information", "data lifecycle and representation"),
            ("Software design process", "requirements, algorithms, testing"),
            ("Data storytelling", "insights, visualisation, ethics"),
        ]
        created_topics: list[Topic] = []
        for subject_code, subject in subjects_by_code.items():
            for unit in [1, 2, 3, 4]:
                for idx, (title_base, skill) in enumerate(
                    topic_templates[:2] if unit <= 2 else topic_templates[2:], 1
                ):
                    title = f"{title_base} (Unit {unit})"
                    existing = db.scalar(
                        select(Topic).where(
                            Topic.subject_id == subject.id, Topic.unit == unit, Topic.order == idx
                        )
                    )
                    if existing:
                        created_topics.append(existing)
                        continue
                    topic = Topic(
                        subject_id=subject.id,
                        unit=unit,
                        aos=f"AOS {idx}",
                        outcome=f"Outcome {idx}",
                        title=title,
                        order=idx,
                        key_skills_json={
                            "skills": [skill, f"unit-{unit}-{subject_code.lower()} application"]
                        },
                    )
                    db.add(topic)
                    db.commit()
                    db.refresh(topic)
                    created_topics.append(topic)

        for topic in created_topics:
            existing_lessons = db.scalars(select(Lesson).where(Lesson.topic_id == topic.id)).all()
            if existing_lessons:
                continue
            db.add_all(
                [
                    Lesson(
                        topic_id=topic.id,
                        title=f"{topic.title} - Core Concepts",
                        content_md=(
                            f"# {topic.title}\n\n"
                            "## Why this matters\n"
                            "- Exam relevance\n"
                            "- Real-world context\n\n"
                            "## Worked Example\n"
                            "Use the template in Exam Skills and map each sentence to a mark."
                        ),
                        estimated_minutes=25,
                    ),
                    Lesson(
                        topic_id=topic.id,
                        title=f"{topic.title} - Applied Example",
                        content_md=(
                            "### Scenario\nA school needs a better system for managing submissions.\n\n"
                            "### Steps\n1. Identify requirements\n2. Propose data/algorithm approach\n3. Justify testing plan"
                        ),
                        estimated_minutes=20,
                    ),
                ]
            )
            db.commit()

        question_count = db.scalar(select(func.count(Question.id))) or 0
        if question_count < 40:
            # Clear old autogenerated questions while preserving any hand-authored records.
            auto_questions = db.scalars(
                select(Question).where(Question.prompt_md.like("%[AUTO-SEED]%"))
            ).all()
            for q in auto_questions:
                db.delete(q)
            db.commit()

            types = ["mcq", "short", "explain_justify", "code", "data", "skill_drill"]
            styles = ["case_study", "short", "extended", "interpretation", "tracing"]
            command_terms = ["describe", "explain", "analyse", "justify", "evaluate"]
            idx = 0
            for topic in created_topics:
                for local_i in range(3):
                    q_type = types[idx % len(types)]
                    exam_style = styles[idx % len(styles)]
                    marks = 1 + (idx % 4)
                    prompt = (
                        f"[AUTO-SEED] {topic.title}: {q_type} practice question #{local_i + 1}. "
                        f"Respond using the command term '{command_terms[idx % len(command_terms)]}'."
                    )
                    common_kwargs = dict(
                        topic_id=topic.id,
                        type=q_type,
                        exam_style=exam_style,
                        command_terms=[command_terms[idx % len(command_terms)]],
                        marks=marks,
                        difficulty=1 + (idx % 5),
                        prompt_md=prompt,
                        case_material_md=(
                            "Case material: A client wants reliable, ethical and testable outcomes."
                            if exam_style == "case_study"
                            else None
                        ),
                    )

                    if q_type == "mcq":
                        question = Question(
                            **common_kwargs,
                            options_json={
                                "A": "Option A",
                                "B": "Option B",
                                "C": "Option C",
                                "D": "Option D",
                            },
                            correct_json={
                                "answer": "a",
                                "worked_exemplar": "Select A because it best satisfies the requirement and justify with one constraint.",
                            },
                            rubric_json={
                                "keywords": ["requirement", "constraint"],
                                "reasoning_terms": ["because"],
                            },
                        )
                    elif q_type in {"short", "explain_justify", "skill_drill"}:
                        question = Question(
                            **common_kwargs,
                            correct_json={
                                "worked_exemplar": "Define term -> apply to case -> conclude implication."
                            },
                            rubric_json={
                                "keywords": ["requirement", "testing", "stakeholder"],
                                "reasoning_terms": ["because", "therefore", "so"],
                            },
                        )
                    elif q_type == "code":
                        question = Question(
                            **common_kwargs,
                            starter_code="def solve(x):\n    return x\n",
                            tests_public="assert solve(2) == 2",
                            tests_hidden="assert solve(5) == 5",
                            correct_json={
                                "worked_exemplar": "Use a simple function and confirm with tests."
                            },
                            rubric_json={
                                "keywords": ["function", "test"],
                                "reasoning_terms": ["because"],
                            },
                        )
                    else:  # data
                        question = Question(
                            **common_kwargs,
                            correct_json={
                                "expected_values": ["42", "0.84"],
                                "worked_exemplar": "Calculate metric, interpret trend, mention limitation.",
                            },
                            rubric_json={
                                "keywords": ["trend", "evidence"],
                                "interpretation_keywords": ["trend", "limitation", "implication"],
                            },
                        )
                    db.add(question)
                    idx += 1
            db.commit()

        for subject in subjects_by_code.values():
            for unit in [1, 2]:
                title = f"{subject.name} Unit {unit} Mini Project"
                existing = db.scalar(
                    select(Project).where(
                        Project.subject_id == subject.id,
                        Project.unit == unit,
                        Project.title == title,
                    )
                )
                if existing:
                    continue
                db.add(
                    Project(
                        subject_id=subject.id,
                        unit=unit,
                        title=title,
                        brief_md=(
                            f"Design and build a small {subject.name.lower()} solution for Unit {unit}.\n"
                            "Include planning, implementation artefact, and reflection."
                        ),
                        rubric_json={
                            "criteria": [
                                {"name": "Planning quality", "max": 4},
                                {"name": "Implementation quality", "max": 6},
                                {"name": "Reflection quality", "max": 4},
                            ]
                        },
                    )
                )
        db.commit()

        for subject in subjects_by_code.values():
            template_title = f"SAT Template - {subject.name}"
            sat = db.scalar(
                select(SATProject).where(
                    SATProject.user_id == demo_user.id,
                    SATProject.subject_id == subject.id,
                    SATProject.title == template_title,
                )
            )
            if not sat:
                sat = SATProject(
                    user_id=demo_user.id,
                    subject_id=subject.id,
                    title=template_title,
                    context_md="Template SAT context for planning Part 1 and Part 2 evidence.",
                )
                db.add(sat)
                db.commit()
                db.refresh(sat)
            for part in [1, 2]:
                milestone = db.scalar(
                    select(SATMilestone).where(
                        SATMilestone.sat_project_id == sat.id, SATMilestone.part == part
                    )
                )
                if milestone:
                    continue
                db.add(
                    SATMilestone(
                        sat_project_id=sat.id,
                        part=part,
                        checklist_json={
                            "items": [
                                "Define goal and constraints",
                                "Document decision rationale",
                                "Capture testing and feedback evidence",
                                "Write reflective improvements",
                            ]
                        },
                        status_json={"completed": []},
                        due_dates_json={},
                    )
                )
            db.commit()

        total_questions = db.scalar(select(func.count(Question.id))) or 0
        print("Seeding complete.")
        print(
            f"Subjects: {len(subjects_by_code)} | Topics: {len(created_topics)} | Questions: {total_questions}"
        )
        print("Demo user: student@example.com / ChangeMe123!")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
